name = "ArtSet"
uuid = "657d34fe-3196-4c2a-8906-b42f7ce4733b"
authors = ["0G3NES1S"]
version = "0.1.0"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
